server:
  port: 31500
spring:
  application:
    name: xcEdu-order
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_order?characterEncoding=utf-8
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  rabbitmq:
    host: 192.168.222.131
    port: 5672 # 默认就是该端口
    username: xcEdu
    password: xcEdu
    virtualHost: /xcEdu
    listener:
      simple:
        acknowledge-mode: manual # 消息接收后进行手动确认
        prefetch: 1 # 每个消费者同时只能处理一条消息
    template:
      exchange: xcEdu.order.exchange # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      retry:
        enabled: true # 是否支持重试
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      mandatory: true # 开启强制委托模式
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送到交换机(Exchange)，如果发送失败会有错误回执，从而触发重试
    publisher-returns: true # 生产者确认机制，确保消息从交换机(Exchange)发送到对应队列(queue)，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息的间隔时间，单位s，默认为30秒
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
xuecheng:
  mq:
    exchange: xcEdu.learning.choosecourse.exchange # 交换机名称
    queue_finish: queue_learning_finish_choosecourse # 队列名称
    routingKey_finish: xcEdu.finish.choosecourse.routingkey # 路由键名称
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间