server:
  port: 31200
spring:
  application:
    name: xcEdu-course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  # 初始建立连接数量
      minIdle: 5  # 最小连接数量
      maxActive: 20 # 最大连接数量
      maxWait: 10000  # 获取连接最大等待时间，毫秒
      testOnBorrow: true # 申请连接时检测连接是否有效
      testOnReturn: false # 归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000 # 连接在连接池的最小生存时间（毫秒）
  security:
    user:
      name: huangmuchen
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka,http://localhost:50102/eureka/
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息的间隔时间，单位s，默认为30秒
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.xuecheng.model.domain.course # 起别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志到控制台，查看执行的sql语句
# 设置feign调用超时时间
ribbon:
  ConnectTimeout: 10000 # 连接请求
  ReadTimeout: 20000 # 调用请求
course-publish:
  siteId: 5e5b6b8aa6a4ac40046c05ee
  templateId: 5e5a72e4a6a4ac414c52ed7a
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/