server:
  port: 31001
spring:
  application:
    name: xcEdu-cms
  freemarker:
    cache: false # 关闭模板缓存，及时刷新，方便测试
    settings:
      template_update_delay: 0 # 检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.222.131
    port: 5672 # 默认就是该端口
    username: xcEdu
    password: xcEdu
    virtualHost: /xcEdu
    template:
      exchange: xcEdu.cms.releasePage.exchange # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      retry:
        enabled: true # 是否支持重试
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      mandatory: true # 开启强制委托模式
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送到交换机(Exchange)，如果发送失败会有错误回执，从而触发重试
    publisher-returns: true # 生产者确认机制，确保消息从交换机(Exchange)发送到对应队列(queue)，如果发送失败会有错误回执，从而触发重试
  security:
    user:
      name: huangmuchen
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka,http://localhost:50102/eureka/
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息的间隔时间，单位s，默认为30秒
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}