server:
  port: 40100
spring:
  application:
    name: xcEdu-search
xuecheng:
  elasticsearch:
    hostList: 127.0.0.1:9200,127.0.0.1:9201,127.0.0.1:9202 #多个结点中间用逗号分隔
    courseIndex: xc_course
    courseType: doc
    courseSourceFields: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time
    mediaIndex: xc_course_media
    mediaType: doc
    mediaSourceFields: courseid,media_id,media_url,teachplan_id,media_fileoriginalname
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息的间隔时间，单位s，默认为30秒
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
